import { RankData } from '../viewmodel/RankData';

export {rankData1,rankData2}
const rankData1: RankData[] = [
  new RankData('1',$r('app.string.fruit_apple'),'30000'),
  new RankData('2',$r('app.string.fruit_watermelon'),'15000'),
  new RankData('3',$r('app.string.fruit_red_grape'),'13000'),
  new RankData('4',$r('app.string.fruit_pineapple'),'9000'),
  new RankData('5',$r('app.string.fruit_pears'),'5000'),
  new RankData('6',$r('app.string.fruit_guava'),'4300'),
  new RankData('7',$r('app.string.fruit_durian'),'3000'),
  new RankData('8',$r('app.string.fruit_carambola'),'1800'),
  new RankData('9',$r('app.string.fruit_banana'),'1000'),
  new RankData('10',$r('app.string.fruit_grapes'),'800')
];

const  rankData2: RankData[] = [
  new RankData('11',$r('app.string.fruit_watermelon'),'18000'),
  new RankData('12',$r('app.string.fruit_apple'),'17600'),
  new RankData('13',$r('app.string.fruit_pears'),'15000'),
  new RankData('14',$r('app.string.fruit_pineapple'),'14333'),
  new RankData('15',$r('app.string.fruit_red_grape'),'13000'),
  new RankData('16',$r('app.string.fruit_guava'),'9000'),
  new RankData('17',$r('app.string.fruit_durian'),'5000'),
  new RankData('18',$r('app.string.fruit_carambola'),'1000'),
  new RankData('19',$r('app.string.fruit_banana'),'90'),
  new RankData('20',$r('app.string.fruit_grapes'),'50')
];
